# Generated by Django 2.1.2 on 2018-10-11 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBMag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arol_code', models.CharField(max_length=12)),
                ('commercial_code', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('supplementary_description', models.TextField()),
            ],
            options={
                'verbose_name': 'componente',
                'verbose_name_plural': 'componenti',
            },
        ),
        migrations.CreateModel(
            name='Famiglia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Macro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macro', models.CharField(max_length=10)),
                ('componenti', models.ManyToManyField(to='distinte.DBMag')),
                ('famiglia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distinte.Famiglia')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='macro',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distinte.Marca'),
        ),
        migrations.AddField(
            model_name='macro',
            name='tags',
            field=models.ManyToManyField(to='distinte.Tag'),
        ),
        migrations.AddField(
            model_name='dbmag',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distinte.Marca'),
        ),
    ]
