# Generated by Django 2.1.1 on 2018-09-11 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduli', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sigla',
            old_name='nome',
            new_name='sigla',
        ),
    ]
