# Generated by Django 2.1.1 on 2018-09-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduli', '0002_auto_20180911_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sigla',
            name='descrizione',
            field=models.CharField(max_length=60),
        ),
    ]
