# Generated by Django 2.1.1 on 2018-10-02 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduli', '0004_auto_20181001_2212'),
    ]

    operations = [
    ]
