# Generated by Django 2.1.1 on 2018-10-02 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181002_2004'),
        ('moduli', '0005_auto_20181002_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sigla',
            name='traduzione',
        ),
        migrations.AddField(
            model_name='sigla',
            name='traduzioni',
            field=models.ManyToManyField(through='moduli.Traduzione', to='core.Lingua'),
        ),
        migrations.AddField(
            model_name='traduzione',
            name='sigla',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='moduli.Sigla'),
            preserve_default=False,
        ),
    ]
