# Generated by Django 2.1.1 on 2018-10-02 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduli', '0006_auto_20181002_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sigla',
            name='traduzioni',
        ),
    ]
