# Generated by Django 2.1.1 on 2018-10-02 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181002_2004'),
        ('moduli', '0007_remove_sigla_traduzioni'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='traduzione',
            unique_together={('sigla', 'lingua')},
        ),
    ]
