# Generated by Django 2.1.2 on 2018-10-11 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduli', '0009_auto_20181003_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_modulo', models.CharField(max_length=20)),
                ('descrizione', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'moduli',
            },
        ),
        migrations.CreateModel(
            name='TipoModulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'tipo di modulo',
                'verbose_name_plural': 'tipi di modulo',
            },
        ),
        migrations.AddField(
            model_name='modulo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduli.TipoModulo'),
        ),
    ]
