# Generated by Django 2.1.2 on 2018-10-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduli', '0010_auto_20181011_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='opzione',
            field=models.BooleanField(default=False),
        ),
    ]
