# Generated by Django 2.1.2 on 2018-10-12 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduli', '0011_modulo_opzione'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiglaInModulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etichetta', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='id_modulo',
        ),
        migrations.AlterField(
            model_name='modulo',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='siglainmodulo',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduli.Modulo'),
        ),
        migrations.AddField(
            model_name='siglainmodulo',
            name='sigla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduli.Sigla'),
        ),
    ]
