# Generated by Django 2.1.2 on 2019-01-17 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduli', '0012_auto_20181012_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sigla',
            name='tipo',
        ),
        migrations.AlterUniqueTogether(
            name='traduzione',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='traduzione',
            name='lingua',
        ),
        migrations.RemoveField(
            model_name='traduzione',
            name='sigla',
        ),
        migrations.AlterField(
            model_name='siglainmodulo',
            name='sigla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigle.Sigla'),
        ),
        migrations.DeleteModel(
            name='Sigla',
        ),
        migrations.DeleteModel(
            name='Tipo_componente',
        ),
        migrations.DeleteModel(
            name='Traduzione',
        ),
    ]
