# Generated by Django 2.1.1 on 2018-10-01 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181001_2146'),
    ]

    operations = [
    ]
