# Generated by Django 2.1.1 on 2018-10-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_auto_20181001_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lingua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lingua', models.CharField(max_length=20)),
                ('originale', models.CharField(max_length=20)),
                ('sigla', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'lingua',
                'verbose_name_plural': 'lingue',
            },
        ),
    ]
