# Generated by Django 2.1.1 on 2018-10-02 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lingua'),
    ]

    operations = [
    ]
