# Generated by Django 2.1.1 on 2018-10-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181002_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lingua',
            name='sigla',
        ),
        migrations.AlterField(
            model_name='lingua',
            name='id',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
