# Generated by Django 2.1.2 on 2019-01-17 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_auto_20181002_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sigla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(help_text='Lunghezza massima 5 caratteri', max_length=5)),
                ('descrizione', models.CharField(help_text='Lunghezza massima 60 caratteri', max_length=60)),
            ],
            options={
                'verbose_name_plural': 'sigle',
            },
        ),
        migrations.CreateModel(
            name='Tipo_componente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('prefisso', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'verbose_name': 'tipologia di componente',
                'verbose_name_plural': 'tipologie di componenti',
            },
        ),
        migrations.CreateModel(
            name='Trad_sigla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traduzione', models.CharField(max_length=60)),
                ('lingua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Lingua')),
                ('sigla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigle.Sigla')),
            ],
            options={
                'verbose_name': 'traduzione sigla',
                'verbose_name_plural': 'traduzioni sigle',
            },
        ),
        migrations.AddField(
            model_name='sigla',
            name='tipo',
            field=models.ForeignKey(help_text='Seleziona da lista', on_delete=django.db.models.deletion.CASCADE, to='sigle.Tipo_componente'),
        ),
        migrations.AlterUniqueTogether(
            name='trad_sigla',
            unique_together={('sigla', 'lingua')},
        ),
    ]
